name: Test

on:
  pull_request:
    branches:
      - master
      - 'feature/**'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: luizm/action-sh-checker@v0.8.0
      env:
        SHFMT_OPTS: -i 2 -ci -s -d
